
spring.profiles.active : prod

spring:
  postgres:
  console:
  enabled: true
  
  application:
    name: INVENTORY-MANEGEMENT
  
  
    logging:
        level.org.springframework.cloud.sleuth : DEBUG